name: GitHub Actions Demo
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: Use nodeJs version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i 
      - run: echo finished npm i."
      - run: npm run build
      - run: echo finished npm build."
      - run: npm run start
      - run: started the project"
