name: GitHub Actions Demo
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i --ignore-scripts
      # - run: npm install
      - name: Build
        run: npm run build
      - run: pm2 restart all
