name: GitHub Actions Demo
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: cache node modules
        id: myCacheStep
        uses: actions/cache@v3
        env: 
          cache-name: cache-node-modules
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          warn-if-changed: true
          restore-keys: | 
            ${{ runner.os }}-build-${{ env.name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}
      - name: install node modules
        if: steps.myCacheStep.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run build
      - run: pm2 restart all
