name: GitHub Actions Demo
on: 
  push:
    branches:
      - develop
  # pull_request:
  #   branches:
  #     - develop
env:
  POSTGRES_HOST: database-1.clujym4xkmgv.us-east-1.rds.amazonaws.com
  POSTGRES_PORT: 5432
  DB_TYPE: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DATABASE: nset
  MODE: DEV
  RUN_MIGRATIONS: true
  TYPEORM_SYNC: true
  TYPEORM_LOGGING: true
  PORT: 3000
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - uses: actions/checkout@v3
      - run: npm run build
      - run: pm2 restart all
